version: "3.9"
services:
  web:
    build: app/
    environment:
      - DB_HOST=db
      - DB_CONNECTION_POOL_SIZE=100
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    ports:
      - 8080:8080
    depends_on:
      db_migration:
        condition: service_completed_successfully
      db:
        condition: service_started
  db_migration:
    image: migrate/migrate:v4.17.0
    entrypoint: /bin/sh
    command:
      [
        "./wait_for.sh",
        "db:5432",
        "--",
        "migrate",
        "-path=/migrations/",
        "-database",
        "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslm\
          ode=disable",
        "up"
      ]
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=db
    volumes:
      - ./app/migrations:/migrations
      - ./wait_for.sh:/wait_for.sh
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
